In [1]:
# Dependencies and Setup
import pandas as pd
import requests
import gmaps

# Import API key
from config import g_key

# Configure gmaps API key
gmaps.configure(api_key=g_key)

In [2]:
# 1. Import the WeatherPy_database.csv file. 
city_data_df = pd.read_csv("../Weather_Database/WeatherPy_Database.csv")
city_data_df.head()

,City_ID,City,Country,Lat,Lng,Max Temp,Humidity,Cloudiness,Wind Speed,Current Description
0,0,Grand Forks,US,47.9417,-97.4337,82.78,57,20,3.44,few clouds
1,1,Svetlaya,RU,46.5389,138.3297,63.70,93,100,8.23,overcast clouds
2,2,Basco,PH,20.4487,121.9702,83.77,75,7,11.83,clear sky
3,3,Ribeira Grande,PT,38.5167,-28.7000,70.20,64,40,6.91,scattered clouds
4,4,Paris,FR,48.8534,2.3488,77.07,51,0,12.66,clear sky

In [3]:
# 5a. Create DataFrame called hotel_df to store hotel names along with city, country, max temp, and coordinates.
hotel_df = city_data_df[["City", "Country", "Max Temp", "Current Description", "Lat", "Lng"]].copy()

# 5b. Create a new column "Hotel Name"
hotel_df["Hotel Name"] = ""
hotel_df = hotel_df.head(15)
hotel_df

,City,Country,Max Temp,Current Description,Lat,Lng,Hotel Name
0,Grand Forks,US,82.78,few clouds,47.9417,-97.4337,
1,Svetlaya,RU,63.70,overcast clouds,46.5389,138.3297,
2,Basco,PH,83.77,clear sky,20.4487,121.9702,
3,Ribeira Grande,PT,70.20,scattered clouds,38.5167,-28.7000,
4,Paris,FR,77.07,clear sky,48.8534,2.3488,
5,Leningradskiy,RU,37.62,overcast clouds,69.3833,178.4167,
6,Atuona,PF,77.38,broken clouds,-9.8000,-139.0333,
7,Avarua,CK,75.25,broken clouds,-21.2078,-159.7750,
8,Kibala,TD,80.55,few clouds,9.1104,18.3463,
9,Butaritari,KI,82.13,light rain,3.0707,172.7902,
10,Tari,NG,85.06,light rain,12.4086,4.4914,
11,Lebu,CL,50.70,clear sky,-37.6167,-73.6500,
12,Chuy,UY,69.64,scattered clouds,-33.6971,-53.4616,
13,Kodiak,US,55.89,broken clouds,57.7900,-152.4072,
14,Georgetown,MY,83.89,thunderstorm,5.4112,100.3354,

In [4]:
# 6a. Set parameters to search for hotels with 5000 meters.
params = {
    "radius": 5000,
    "type": "lodging",
    "key": g_key
}

In [5]:

# 6b. Iterate through the hotel DataFrame.
for index, row in hotel_df.iterrows():
    # 6c. Get latitude and longitude from DataFrame
    lat = row["Lat"]
    lng = row["Lng"]
    
    params["location"] = f'{lat},{lng}'
    # 6d. Set up the base URL for the Google Directions API to get JSON data.
    base_url = "https://maps.googleapis.com/maps/api/place/nearbysearch/json"
    

    # 6e. Make request and retrieve the JSON data from the search. 
    hotels = requests.get(base_url, params=params).json()
   
    
    # 6f. Get the first hotel from the results and store the name, if a hotel isn't found skip the city.
    try:
        hotel_df.loc[index, "Hotel Name"] = hotels["results"][0]["name"]
    except (IndexError):
        print("Hotel not found... skipping.")

Hotel not found... skipping.
Hotel not found... skipping.

In [6]:
# 8a. Create the output File (CSV)
output_data_file = '../Vacation_Search/WeatherPy_Vacation_v2.csv'

# 8b. Export the City_Data into a csv
hotel_df.to_csv(output_data_file, index_label="City_ID")